[build]
  # This is the directory to publish, which contains your site's HTML, CSS, and JS
  publish = "src/"
  # This is the directory where Netlify Functions are stored
  functions = "netlify/functions/"

[functions]
  # Specifies the Node.js version for your functions
  node_bundler = "esbuild"
  node_version = "20"
